version: "3.8"

services:
  app:
    container_name: app
    build: .
    image: app
    ports:
      - "8000:8000"
    links:
      - mongodb
  postgres:
    container_name: postgres_db
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4:8.2
      env_file:
        - .env
      ports:
        - "5050:80"