version: '3.8'
services:
  jenkins:
    image: jenkins
    container_name: jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins-volume:/var/jenkins_home
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry-volume:/var/lib/registry:rw

volumes:
  jenkins-volume:
  registry-volume: