version: '3.8'
services:
  jenkins:
    image: jenkins
    container_name: jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins-volume:/var/jenkins_home
      # Mount host docker.sock so that jenkins container can run containerized agents
      # For better experience with running dockerized agents it is advised to set up jenkins as dind
      - //var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry-volume:/var/lib/registry:rw
volumes:
  jenkins-volume:
  registry-volume: